- name: Manage static route
  hosts: localhost
  become: yes
  tasks:
    - name: Remove existing static route if present
      community.general.ip_route:
        dest: "192.168.1.0/24"
        via: "192.168.1.1"
        dev: "enp1s0"
        state: "absent"
      ignore_errors: yes  

    - name: Add static route
      community.general.ip_route:
        dest: "192.168.1.0/24"
        via: "192.168.1.1"
        dev: "enp1s0"
        state: "present"
