- name: Add static route
  hosts: localhost
  become: yes
  tasks:
    - name: Remove existing 
      shell: |
        ip route del 172.31.33.236/20 via 192.168.1.1 dev enp1s0 || true

    - name: Add static route
      shell: |
        ip route add 192.168.1.0/24 via 192.168.1.1 dev enp1s0
      when: "'192.168.1.0/24' not in lookup('pipe', 'ip route show')"
      # I want to write pytest for aws in which i want i can give ssm parameter tag name you need to validate that how many number of ssm parameter store can have same tag and oi also provide you a number then you can validate that weather number is equal or not

      <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Office Login</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        .login-container {
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            width: 300px;
        }
        h2 {
            text-align: center;
            margin-bottom: 20px;
        }
        .form-group {
            margin-bottom: 15px;
        }
        label {
            display: block;
            margin-bottom: 5px;
        }
        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 8px;
            border: 1px solid #ddd;
            border-radius: 4px;
        }
        button {
            width: 100%;
            padding: 10px;
            background-color: #5cb85c;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
        }
        button:hover {
            background-color: #4cae4c;
        }
        .error-message {
            color: red;
            text-align: center;
            margin-top: 10px;
        }
    </style>
</head>
<body>
    <div class="login-container">
        <h2>Office Login</h2>
        <form id="loginForm">
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" id="password" name="password" required>
            </div>
            <button type="submit">Login</button>
            <div class="error-message" id="errorMessage"></div>
        </form>
    </div>

    <script>
        document.getElementById('loginForm').addEventListener('submit', function(event) {
            event.preventDefault(); // Prevent default form submission

            const username = document.getElementById('username').value;
            const password = document.getElementById('password').value;
            const errorMessage = document.getElementById('errorMessage');

            // Simple validation (you can customize this)
            if (username && password) {
                // Redirect to the admin dashboard page
                window.location.href = "admin.html"; // Change to the appropriate admin page
            } else {
                errorMessage.textContent = 'Please enter your credentials.';
            }
        });
    </script>
</body>
</html>
